"""Root conftest: command-line options must live here to be seen for whole-suite runs.

Everything else (fixtures) is in tests/conftest.py.
"""
from pathlib import Path


def pytest_addoption(parser):
	parser.addoption(
		"--matrix-out",
		action="store",
		default=None,
		help="write the route x role smoke matrix to this markdown file after the run",
	)


def pytest_sessionfinish(session, exitstatus):
	out = session.config.getoption("--matrix-out")
	if not out:
		return
	from tests.helpers import MATRIX_RESULTS

	if not MATRIX_RESULTS:
		return
	personas = ["anon", "student", "mod", "admin", "imp_admin", "api_student", "api_mod", "api_admin"]
	lines = [
		"# Route x role smoke matrix",
		"",
		"Generated by `pytest tests/test_route_matrix.py --matrix-out docs/ROUTE_ROLE_MATRIX.md`. Do not edit by hand.",
		"",
		"Cell = HTTP status observed. `-` = persona not applicable to that surface.",
		"Web personas hold a session (staff after /switch-role; `imp_admin` is an admin impersonating a student).",
		"API personas send X-API-Key / X-API-Secret headers only.",
		"",
		"| Method | Rule | " + " | ".join(personas) + " |",
		"|---|---|" + "---|" * len(personas),
	]
	for (rule, method), results in sorted(MATRIX_RESULTS.items(), key=lambda item: (item[0][0], item[0][1])):
		cells = [str(results.get(p, "-")) for p in personas]
		lines.append(f"| {method} | `{rule}` | " + " | ".join(cells) + " |")
	Path(out).parent.mkdir(parents=True, exist_ok=True)
	Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")
